### ISSUE TITLE
Getting error "The JSON file could not be read"

### ISSUE THREAD

**Issue by psychsatani** [kometenstaub/linked-data-vocabularies#19]
I am on the latest obsidian build 0.13.19 and getting this error on Mac when I run the command Query LCSH. I can see the 3 json files in my folder so not sure what is wrong.

**Comment by kometenstaub** [comment]
Did you input the folder path in the settings? If you did that and it still cannot read it, try checking in the console (`Cmd-Opt-I`) if there are errors.

**Comment by kometenstaub** [comment]
See this: https://github.com/kometenstaub/obsidian-linked-data-vocabularies#configuration

**Comment by kometenstaub** [comment]
Closing because no response.
