### ISSUE TITLE
Vocabulary Restricted to Musical Instruments

### ISSUE THREAD

**Issue by jeetsukumaran** [kometenstaub/linked-data-vocabularies#28]
Awesome plugin!

I followed the instructions and got everything hooked up.

However, the suggestions that all come up are musical instruments, rather than subject headings.

![image](https://github.com/kometenstaub/linked-data-vocabularies/assets/26183/f48dc437-3002-4f2b-8d05-4c81c0eaaddf)

Following the [instructions](https://github.com/kometenstaub/linked-data-helper), I downloaded the ``subjects.madsrdf.jsonld.gz`` file  instructions from <https://id.loc.gov/download/> and converted it. Everything seems to work fine, except the data is unexpected. Did I download the wrong file?

**Comment by jeetsukumaran** [comment]
Oh, I'm such an idiot!

![image](https://github.com/kometenstaub/linked-data-vocabularies/assets/26183/8b1ffd8b-3420-4ee4-b2ad-4e0d0490b280)

I converted the wrong file! 

(Though this opens up the possibility of this plugin supporting multiple vocabularies ??)

**Comment by kometenstaub** [comment]
> (Though this opens up the possibility of this plugin supporting multiple vocabularies ??)

Looks like it, yes. Although it would probably require a rewrite of both plugins to be more general in the data it accepts.
