### ISSUE TITLE
Command LCSH not loading for me in command palette?

### ISSUE THREAD

**Issue by Garg0yle** [kometenstaub/linked-data-vocabularies#29]
Hi there, bonkers excited for this plug-in. I'm trying to set it up now. I have successfully unzipped the file and put in the folder path to where the Json files are stored in my vault attachment folder. I then closed and restarted Obsidian. However when I open the command pallete, I do not see any commands related to linked data or LCSH. Any ideas?Thanks!

**Comment by kometenstaub** [comment]
> I have successfully unzipped the file and put in the folder path to where the Json files are stored in my vault attachment folder.

That doesn’t sound right. Did you follow the instructions correctly?

**Comment by kometenstaub** [comment]
Please let me know if 2.0.7 fixes it.

**Comment by kometenstaub** [comment]
Alright, I figured out what the issue was. When I updated the config to work with the newer build tool version, I accidentally removed something that was necessary. I've tested it and now it works again. Please let me know if it also works for you now.

**Comment by kometenstaub** [comment]
Thanks for confirming!
